import EntryContainer from "@/components/EntryContainer/EntryContainer";
import ThemeToggler from "@/components/Layout/ThemeToggler";
import LoadingScreen from "@/components/LoadingScreen/LoadingScreen";
import SeaCargo from "@/components/SVG/SeaCargo";
import Head from "next/head";
import React from "react";
import { ToastContainer } from "react-toastify";

function index() {
  return (
    <>
      <Head>
        <title>SeaCargo | Entry</title>
        <meta name="seacargo" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative flex min-h-screen">
        <LoadingScreen />
        <div className="fixed right-5 top-5 z-50">
          <ThemeToggler />
        </div>
        <div className="relative z-10 h-screen w-[50vw] overflow-hidden bg-prim-light dark:bg-prim-dark max-tablet:hidden">
          <SeaCargo className="animate-ship_sail absolute -bottom-[10%] -left-[70%] h-auto w-[80vw] fill-white dark:fill-prim-dkbg" />
          <h1 className="absolute right-5 top-5 text-[2.5rem] font-bold text-white dark:text-prim-dkbg">
            SeaCargo
          </h1>
        </div>
        <EntryContainer />
        <ToastContainer />
      </main>
    </>
  );
}

export default index;
