import Button from "@/components/Button/Button";
import { deleteCookie } from "cookies-next";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect } from "react";

function index() {
  const router = useRouter();
  useEffect(() => {
    deleteCookie("accessToken");
  }, []);
  return (
    <>
      <Head>
        <title>SeaCargo | Unauthorized</title>
        <meta name="seacargo" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen w-screen flex-col items-center justify-center gap-5">
        <p>401 | Unauthorized Token Expired</p>
        <Button
          type="button"
          onClick={() => router.push("/entry")}
          primary
          name="goto-entry"
          large
        >
          Go to Enty Page
        </Button>
      </div>
    </>
  );
}

export default index;
