import Layout from "@/components/Layout/Layout";
import React, { ReactElement } from "react";
import { NextPageWithLayout } from "../_app";
import SeaCargo from "@/components/SVG/SeaCargo";
import Head from "next/head";

const index: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>SeaCargo | User</title>
        <meta name="seacargo" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative flex min-h-screen max-w-[1000px] items-center justify-center pt-24 tablet:max-w-none">
        <SeaCargo className="animate-ship_sail_onsite w-[50%] fill-prim-light dark:fill-prim-dark" />
      </main>
    </>
  );
};

index.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default index;
