import CreateShippingForm from "@/components/CreateShippingForm/CreateShippingForm";
import Layout from "@/components/Layout/Layout";
import LoadingScreen from "@/components/LoadingScreen/LoadingScreen";
import { NextPageWithLayout } from "@/pages/_app";
import { useShipping } from "@/store/shipping/useShipping";
import { getCookie } from "cookies-next";
import Head from "next/head";
import React, { ReactElement, useEffect } from "react";

const index: NextPageWithLayout = () => {
  const userAddresses = useShipping.use.userAddresses();
  const selectedAddress = useShipping.use.selectedAddress();
  const { getUserAddresses } = useShipping.getState();

  useEffect(() => {
    const token = getCookie("accessToken");
    getUserAddresses(token as string);
  }, []);
  return (
    <>
      <Head>
        <title>SeaCargo | User Create Shipping</title>
        <meta name="seacargo" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative min-h-screen max-w-[1000px] pt-24 tablet:max-w-none">
        <div className="h-full w-full tablet:flex tablet:justify-center">
          <LoadingScreen />
          <CreateShippingForm
            userAddresses={userAddresses}
            selectedAddress={selectedAddress}
          />
        </div>
      </main>
    </>
  );
};

index.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default index;
