import LoadingScreen from "@/components/LoadingScreen/LoadingScreen";
import SideBar from "@/components/SideBar/SideBar";
import React, { ReactElement } from "react";
import { NextPageWithLayout } from "../_app";
import AdminLayout from "@/components/Layout/AdminLayout";
import Head from "next/head";

const index: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>SeaCargo | Overview</title>
        <meta name="seacargo" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative flex min-h-screen items-center justify-center px-10 py-5 tablet:ml-[20vw]">
        <iframe
          width="1000"
          height="600"
          src="https://www.youtube.com/embed/iUKouo1KHds?si=-xR3D4FPsIfv95Tv"
          title="YouTube video player"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
        ></iframe>
      </main>
      ;
    </>
  );
};

index.getLayout = function getLayout(page: ReactElement) {
  return <AdminLayout>{page}</AdminLayout>;
};

export default index;
